# Generated by Django 6.0.6 on 2026-07-10 22:12

import api.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.auth.models.CustomUserManager()),
            ],
        ),
    ]
