# Generated by Django 6.0.6 on 2026-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_initiativedocument_initiative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waived', 'Waived'), ('stage_advanced', 'Stage Advanced'), ('reassigned', 'Reassigned'), ('handover', 'Handover'), ('updated', 'Updated')], max_length=30),
        ),
    ]
