# Generated by Django 6.0.6 on 2026-07-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='is_handed_over',
            field=models.BooleanField(default=False),
        ),
    ]
